"""initial_schema

Revision ID: bd7a13c80cbb
Revises: 
Create Date: 2026-09-14 16:13:02.262043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd7a13c80cbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opaque_key', sa.UUID(), nullable=False),
    sa.Column('unit_code', sa.String(length=24), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_is_active'), 'personnel', ['is_active'], unique=False)
    op.create_index(op.f('ix_personnel_opaque_key'), 'personnel', ['opaque_key'], unique=True)
    op.create_index(op.f('ix_personnel_unit_code'), 'personnel', ['unit_code'], unique=False)
    op.create_table('duty_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personnel_id', sa.UUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('duty_type', sa.String(length=24), nullable=False),
    sa.Column('duty_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('deployment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_records_duty_type'), 'duty_records', ['duty_type'], unique=False)
    op.create_index(op.f('ix_duty_records_personnel_id'), 'duty_records', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_duty_records_record_date'), 'duty_records', ['record_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('personnel_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wellness_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personnel_id', sa.UUID(), nullable=False),
    sa.Column('stress_level_self_report', sa.Integer(), nullable=False),
    sa.Column('rest_hours_7d', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sleep_hours_7d', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('workload_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_assessments_personnel_id'), 'wellness_assessments', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_wellness_assessments_submitted_at'), 'wellness_assessments', ['submitted_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('personnel_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_personnel_id'), 'audit_logs', ['personnel_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personnel_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('probability_low', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('probability_medium', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('probability_high', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shap_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=16), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['wellness_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_personnel_id'), 'predictions', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_predictions_review_status'), 'predictions', ['review_status'], unique=False)
    op.create_index(op.f('ix_predictions_risk_level'), 'predictions', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_risk_level'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_review_status'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_personnel_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_audit_logs_personnel_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_wellness_assessments_submitted_at'), table_name='wellness_assessments')
    op.drop_index(op.f('ix_wellness_assessments_personnel_id'), table_name='wellness_assessments')
    op.drop_table('wellness_assessments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_duty_records_record_date'), table_name='duty_records')
    op.drop_index(op.f('ix_duty_records_personnel_id'), table_name='duty_records')
    op.drop_index(op.f('ix_duty_records_duty_type'), table_name='duty_records')
    op.drop_table('duty_records')
    op.drop_index(op.f('ix_personnel_unit_code'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_opaque_key'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_is_active'), table_name='personnel')
    op.drop_table('personnel')
    # ### end Alembic commands ###
