"""add duty record start/end times

Revision ID: c51826e301a9
Revises: bd7a13c80cbb
Create Date: 2026-09-14 17:15:47.136765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51826e301a9'
down_revision: Union[str, None] = 'bd7a13c80cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duty_records', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('duty_records', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duty_records', 'end_time')
    op.drop_column('duty_records', 'start_time')
    # ### end Alembic commands ###
